conky.config = {
  background = false,
  update_interval = 1,
  total_run_times = 1,
  out_to_console = true,
  out_to_x = false,
  double_buffer = false,
  max_text_width = 400,
  use_xft = true,
  font = "JetBrainsMono Nerd Font:size=10",
  alignment = "top_left",
  no_buffers = true,
  short_units = true,
};

conky.text = [[
CPU=${cpu}
MEM=${memperc}
DISK=${fs_used_perc /}
UP=${uptime_short}
]];
